---
title: "`simplerspec` teaching material for infrared spectroscopy applications"
output: rmarkdown::github_document
---

# Getting started with infrared spectroscopy

R has become a very popular environment for statistical computing. 
There is other alternative languages that are equally good, better or worse, depeding on the field of application and personal opinion. 
Here, we solely focus on R.

* **Minimum recommended R knowledge**: Prior to working with spectral data
  using the R environment, you should improve your R scripting/programming
  skills. You can for example consider this document in this repo or the pdf 
  file here. I would highly recommend to do this because being familiar with R 
  basics helps to avoid frustration in the first place and to hopefully enjoy 
  the opportunities spectral analysis provides.

---

# Recommended literature

## Principles and applications of soil spectroscopy

* Awiti, A. O., Walsh, M. G., Shepherd, K. D., & Kinyamario, J.
    (2008). Soil condition classification using infrared spectroscopy: A
    proposition for assessment of soil condition along a tropical
    forest-cropland chronosequence. Geoderma, 143(1–2), 73–84.
    <https://doi.org/10.1016/j.geoderma.2007.08.021>

* Chang, C.-W., Laird, D. A., Mausbach, M. J., & Hurburgh, C. R.
  (2001). Near-infrared reflectance spectroscopy–principal components
  regression analyses of soil properties. Soil Science Society of
  America Journal, 65(2), 480–490.

* Clairotte, M., Grinand, C., Kouakoua, E., Thébault, A., Saby, N. P.
  A., Bernoux, M., & Barthès, B. G. (2016). National calibration of
  soil organic carbon concentration using diffuse infrared reflectance
  spectroscopy. Geoderma, 276, 41–52.
  <https://doi.org/10.1016/j.geoderma.2016.04.021>

* Nocita, M., Stevens, A., van Wesemael, B., Aitkenhead, M., Bachmann,
  M., Barthès, B., … Wetterlind, J. (2015). Chapter Four - Soil
  Spectroscopy: An Alternative to Wet Chemistry for Soil Monitoring.
  In D. L. Sparks (Ed.), Advances in Agronomy (Vol. 132, pp. 139–159).
  Academic Press. Retrieved from
  <http://www.sciencedirect.com/science/article/pii/S0065211315000425>

* Rinnan, Å. (2014). Pre-processing in vibrational spectroscopy –
  when, why and how. Analytical Methods, 6(18), 7124.
  <https://doi.org/10.1039/C3AY42270D>

* Rinnan, Å., Berg, F. van den, & Engelsen, S. B. (2009). Review of
  the most common pre-processing techniques for near-infrared spectra.
  TrAC Trends in Analytical Chemistry, 28(10), 1201–1222.
  <https://doi.org/10.1016/j.trac.2009.07.007>

* Shepherd, K. D., & Markus G. Walsh. (n.d.). Infrared
  spectroscopy—enabling an evidence-based diagnostic surveillance
  approach to agricultural and environmental management in developing
  countries. <https://doi.org/10.1255/jnirs.716>

* Sila, A. M., Shepherd, K. D., & Pokhariyal, G. P. (2016). Evaluating
  the utility of mid-infrared spectral subspaces for predicting soil
  properties. Chemometrics and Intelligent Laboratory Systems, 153,
  92–105. <https://doi.org/10.1016/j.chemolab.2016.02.013>

* Terhoeven-Urselmans, T., Vagen, T.-G., Spaargaren, O., & Shepherd,
  K. D. (2010). Prediction of Soil Fertility Properties from a
  Globally Distributed Soil Mid-Infrared Spectral Library. Soil
  Science Society of America Journal, 74(5), 1792.
  <https://doi.org/10.2136/sssaj2009.0218>

* Viscarra Rossel, R. A., Behrens, T., Ben-Dor, E., Brown, D. J.,
  Demattê, J. A. M., Shepherd, K. D., … Ji, W. (2016). A global
  spectral library to characterize the world’s soil. Earth-Science
  Reviews, 155, 198–230.
  <https://doi.org/10.1016/j.earscirev.2016.01.012>

* Viscarra Rossel, R. A., Walvoort, D. J. J., McBratney, A. B., Janik,
  L. J., & Skjemstad, J. O. (2006). Visible, near infrared, mid
  infrared or combined diffuse reflectance spectroscopy for
  simultaneous assessment of various soil properties. Geoderma,
  131(1–2), 59–75. <https://doi.org/10.1016/j.geoderma.2005.03.007>

* Wold, S., Sjöström, M., & Eriksson, L. (2001). PLS-regression: a
  basic tool of chemometrics. Chemometrics and Intelligent Laboratory
  Systems, 58(2), 109–130.
  <https://doi.org/10.1016/S0169-7439(01)00155-1>

## Principles and application of plant infrared spectroscopy

* Lebot, V, Malapa, R., & Jung, M. (2013). Use of NIRS for the rapid prediction of total N, minerals, sugars and starch in tropical root and tuber crops. New Zealand Journal of Crop and Horticultural Science, 41(3), 144–153. https://doi.org/10.1080/01140671.2013.798335

* Lebot, Vincent, Champagne, A., Malapa, R., & Shiley, D. (2009). NIR Determination of Major Constituents in Tropical Root and Tuber Crop Flours. Journal of Agricultural and Food Chemistry, 57(22), 10539–10547. https://doi.org/10.1021/jf902675n

* van Maarschalkerweerd, M., & Husted, S. (2015). Recent developments in fast spectroscopy for plant mineral analysis. Frontiers in Plant Science, 6. https://doi.org/10.3389/fpls.2015.00169


## Statistical modeling based on spectroscopy

* Chong, I.-G., & Jun, C.-H. (2005). Performance of some variable selection methods when multicollinearity is present. Chemometrics and Intelligent Laboratory Systems, 78(1–2), 103–112. https://doi.org/10.1016/j.chemolab.2004.12.011

* Eriksson, L., Trygg, J., & Wold, S. (2014). A chemometrics toolbox based on projections and latent variables: A chemometrics toolbox based on projections and latent variables. Journal of Chemometrics, 28(5), 332–346. https://doi.org/10.1002/cem.2581

* Friedman, J., Hastie, T., & Tibshirani, R. (2001). The elements of statistical learning (Vol. 1). Springer series in statistics Springer, Berlin. Retrieved from http://statweb.stanford.edu/~tibs/book/preface.ps

* Kuhn, M. (2008). Building Predictive Models in R Using the caret Package. Journal of Statistical Software, Articles, 28(5), 1–26. https://doi.org/10.18637/jss.v028.i05

* Stevens, A., & Ramirez–Lopez, L. (2014). An introduction to the prospectr package. R Package Vignette, Report No.: R Package Version 0.1, 3. Retrieved from ftp://200.236.31.2/CRAN/web/packages/prospectr/vignettes/prospectr-intro.pdf

* Wold, S., Sjöström, M., & Eriksson, L. (2001). PLS-regression: a basic tool of chemometrics. Chemometrics and Intelligent Laboratory Systems, 58(2), 109–130. https://doi.org/10.1016/S0169-7439(01)00155-1

